name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Ubuntu instance
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the SSH private key for authentication
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/samplelaravel/
            git pull
            composer install
            php artisan migrate --seed
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chown -R www-data:www-data bootstrap/cache
            sudo chmod -R 777 storage bootstrap/cache
            sudo chmod -R 777 bootstrap/cache
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
